CREATE DATABASE IF NOT EXISTS c18hnfueyx1vkqu5;
USE c18hnfueyx1vkqu5;

DROP TABLE IF EXISTS burgers;
CREATE TABLE burgers (
    id int NOT NULL AUTO_INCREMENT,
    burger_name varchar(255) NOT NULL,
    createdAt TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

